config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'buildings#index'

  resources :buildings do
    resources :bathrooms do
      resources :critiques
    end
  end

end

app/models/bathroom.rb
class Bathroom < ApplicationRecord
  belongs_to :building
  has_many :critiques
  has_many :tags

  validate :valid_floor
  validates :gender, :floor, :location, presence: true
  validates :location, length: { maximum: 50 }
  validates :floor, length: { maximum: 10 }
  validates_uniqueness_of :location, :scope => [:floor, :building_id]

  before_save :format_input

  # Calculates the average overall rating
  # PRE: At least one rating exists
  # POST: The average is computed
  def average_overall_rating
    critiques = self.critiques
    critiques.reduce(0){ |sum, el| sum + el.overall_rating }.to_f / critiques.size
  end

  # Calculates the average toilet rating
  # PRE: At least one rating exists
  # POST: The average is computed
  def average_toilet_rating
    critiques = self.critiques
    critiques.reduce(0){ |sum, el| sum + el.toilet_rating }.to_f / critiques.size
  end

  # Calculates the average sink rating
  # PRE: At least one rating exists
  # POST: The average is computed
  def average_sink_rating
    critiques = self.critiques
    critiques.reduce(0){ |sum, el| sum + el.sink_rating }.to_f / critiques.size
  end

  # Calculates the average cleanliness rating
  # PRE: At least one rating exists
  # POST: The average is computed
  def average_cleanliness_rating
    critiques = self.critiques
    critiques.reduce(0){ |sum, el| sum + el.cleanliness_rating }.to_f / critiques.size
  end

  # Calculates the average smell rating
  # PRE: At least one rating exists
  # POST: The average is computed
  def average_smell_rating
    critiques = self.critiques
    critiques.reduce(0){ |sum, el| sum + el.smell_rating }.to_f / critiques.size
  end

  # Calculates the average privacy rating
  # PRE: At least one rating exists
  # POST: The average is computed
  def average_privacy_rating
    critiques = self.critiques
    critiques.reduce(0){ |sum, el| sum + el.privacy_rating }.to_f / critiques.size
  end

  private

  # Removes spaces, tabs, etc from beginning and end of input
  # PRE: All inputs are successfully validated
  # POST: Inputs are formatted to the webpage's style
  def format_input
    self.gender = self.gender.strip
    self.floor = self.floor.strip.upcase
    self.location = self.location.strip
  end

  # Checks if the floor number input is a valid
  # PRE: None
  # POST: If invalid, pushes an error to the page
  def valid_floor
    floor = self.floor.to_s
    if !is_number?(floor) && floor.casecmp("L") != 0 && floor.casecmp("LL") != 0 && floor.casecmp("B") != 0 && floor.casecmp("G") != 0
      self.errors[:base] << "Invalid floor"
    end
  end

  # Checks if a string can be parsed to an integer
  # PRE: None
  # POST: None
  def is_number?(obj)
    return obj.to_s == obj.to_i.to_s
  end

end

app/controllers/bathrooms_controller.rb
class BathroomsController < ApplicationController
  before_action :get_building

  # Creates a list of all bathrooms in our database
  def index
    @bathrooms = @building.bathrooms.sort_by{|bathroom| bathroom.floor}
  end

  # Displays a specific bathroom.
  # PRE: The bathroom exists
  # POST: We display info about that bathroom
  def show
    @bathroom = @building.bathrooms.find(params[:id])
  end

  # Redirects to a page for creation of a bathroom
  # PRE: None
  # POST: None
  def new
    @bathroom = @building.bathrooms.new(params[:id])
    @genders = gender_options
    @tags = tag_options
  end

  # Creates and stores a new bathroom in the database
  # PRE: None
  # POST: A new bathroom is saved in the database
  def create
    @bathroom = @building.bathrooms.new(bathroom_params)
    if @bathroom.save
      @bathroom.tags.create(tags_hash)
      redirect_to(building_path(@building))
    else
      render :new
    end
  end

  # Redirects to a page to edit a bathroom
  # PRE: The bathroom exists
  # POST: None
  def edit
    @bathroom = @building.bathrooms.find(params[:id])
    @genders = gender_options
    @tags = tag_options
  end

  # Updates a given bathroom
  # PRE: The bathroom exists
  # POST: Changes to the bathroom are stored in the database
  def update
    @bathroom = @building.bathrooms.find(params[:id])
    if @bathroom.update(bathroom_params)
      @bathroom.tags.destroy_all
      @bathroom.tags.create(tags_hash)
      redirect_to(building_path(@building))
    else
      render :edit
    end
  end

  # Removes a bathroom
  # PRE: The bathroom exists
  # POST: The bathroom is removed from the database
  def destroy
    @bathroom = @building.bathrooms.find(params[:id])
    @bathroom.destroy
    redirect_to(building_bathrooms_path(@building))
  end

  private

  # Specifies the fields that the bathroom has
  # PRE: None
  # POST: None
  def bathroom_params
    params.require(:bathroom).permit(:floor, :location, :gender)
  end

  # Returns form tags from params as an array of hashes
  def tags_hash
    unless params[:bathroom][:tag_ids].nil?
      params[:bathroom][:tag_ids].reject{ |t| t.empty? }.map{ |t| {name: t} }
    else
      {}
    end
  end

  # An array of tags. These will be boolean options that the bathroom has or does not
  def tag_options
    [ 'Only Blow-Driers',
      'Automatic Toilets',
      'Automatic Sinks',
      'Handicap Accessible',
      'Push-Button Sinks',
      'Doors Don\'t Lock',
      'Single Occupant',
      'Has Shower',
      'Bidet',
      'No Urinal Dividers']
  end

  #An array of restroom options.
  #Users registered as male only see Male and Gender-Neutral restrooms
  #Users registered as female only see Female and Gender-Neutral restrooms
  #Users registered as gender-neutral only see Gender-Neutral restrooms
  def gender_options
    ['Male','Female','Gender-Neutral']
  end

  # Finds the specific building with the id
  # PRE: That id is tied with a building
  # POST: None
  def get_building
    @building = Building.find(params[:building_id])
  end
end

app/views/bathrooms/_gender_picture.html.haml
- if bathroom.gender == 'Male'
  = image_tag("male.png")
- elsif bathroom.gender == 'Female'
  = image_tag("female.png")
- else
  = image_tag("unisex.png")

app/views/bathrooms/edit.html.haml
.container
  %h2 Building: #{@building.name}

  - if @bathroom.errors.any?
    %h3
      = pluralize(@bathroom.errors.count, "error")
      prevented this bathroom from being modified:
    %ul
      - @bathroom.errors.full_messages.each do |msg|
        %li= msg
  .col-xs-12.col-sm-5
    = simple_form_for @bathroom, html: {class: 'form-horizontal'}, url: building_bathroom_path(@building,@bathroom) do |f|
      = f.input :gender, collection: @genders
      = f.input :floor
      = f.input :location
      = f.association :tags, collection: @tags, :error => false, as: :check_boxes

      = f.button :submit, :class => 'btn btn-primary'

app/views/bathrooms/index.html.haml
.container
  %h1 Bathrooms
  %h2 Building: #{@building.name}

  = link_to "Create New Bathroom", new_building_bathroom_path(@building), :class => 'btn btn-primary'

  .separator

  %table{:style => "width:100%;", :class => "table table-striped table-hover"}
    - if @bathrooms.empty?
      %div{:class => "panel panel-warning"}
        .panel-heading{ :style => "text-align:center;"}
          = "There are no buildings."
    - else
      %thead
        %tr
          %th Gender
          %th Floor
          %th Location
          %th Actions
      %tbody
        - @bathrooms.each do |bathroom|
          %tr
            %td
              = bathroom.gender
            %td
              = bathroom.floor
            %td
              = bathroom.location
            %td
              = link_to "Show", building_bathroom_path(@building,bathroom), :class => 'btn btn-default'
              = link_to "Edit", edit_building_bathroom_path(@building,bathroom), :class => 'btn btn-default'
              = link_to "Destroy", building_bathroom_path(@building,bathroom), :class => 'btn btn-danger', method: :delete, :data => {confirm: 'Are you sure you want to delete this bathroom?'}

app/views/bathrooms/new.html.haml
.container
  %h2 Building: #{@building.name}

  - if @bathroom.errors.any?
    %h3
      = pluralize(@bathroom.errors.count, "error")
      prevented this bathroom from being added:
    %ul
      - @bathroom.errors.full_messages.each do |msg|
        %li= msg
  .col-xs-12.col-sm-5
    = simple_form_for @bathroom, url: building_bathrooms_path(@building), html: {class: 'form-horizontal'} do |f|
      = f.input :gender, collection: @genders, :error => false
      = f.input :floor, :error => false
      = f.input :location, :error => false
      = f.association :tags, collection: @tags, :error => false, as: :check_boxes

      = f.button :submit, :class => 'btn btn-primary'

app/views/bathrooms/show.html.haml
.container-fluid{:style => 'padding-top:20px;'}
  .col-xs-12.col-sm-4
    .gender-image
      = render partial: 'shared/gender_picture', locals: { bathroom: @bathroom }
  .brnodisplay
    %br
  .col-xs-12.col-sm-8
    .bathroom-text
      %p{:style => 'font-size:40px;'}= @building.name
      %p{:style => 'font-size:20px;'}= 'Floor ' + @bathroom.floor
      %p{:style => 'font-size:20px;'}= @bathroom.location
      %p
        - @bathroom.tags.each do |tag|
          %div{class:"badge badge-pill badge-success"}
            =tag.name
%br
.container-fluid
  - if @bathroom.critiques.empty?
    .panel.panel-warning
      .panel-heading
        This bathroom has not been rated.
  - else
    %h3 Overall Rating: #{'★' * @bathroom.average_overall_rating.round}
    .col-xs-4.col-md-2
      .panel.panel-primary
        .panel-heading
          Toilet
        .panel-body
          - @bathroom.average_toilet_rating.round.times do
            ★
    .col-xs-4.col-md-2
      .panel.panel-primary
        .panel-heading
          Sink
        .panel-body
          - @bathroom.average_sink_rating.round.times do
            ★
    .col-xs-4.col-md-2
      .panel.panel-primary
        .panel-heading
          Cleanliness
        .panel-body
          - @bathroom.average_cleanliness_rating.round.times do
            ★
    .col-xs-4.col-md-2
      .panel.panel-primary
        .panel-heading
          Smell
        .panel-body
          - @bathroom.average_smell_rating.round.times do
            ★
    .col-xs-4.col-md-2
      .panel.panel-primary
        .panel-heading
          Privacy
        .panel-body
          - @bathroom.average_privacy_rating.round.times do
            ★

%br
- if user_signed_in?
  - if critique = current_user.critiques.find_by(bathroom_id: @bathroom.id)
    = link_to "Edit Critique", edit_building_bathroom_critique_path(@building,@bathroom,critique), :class => 'btn btn-primary'
  - else
    = link_to "New Critique", new_building_bathroom_critique_path(@building,@bathroom,critique), :class => 'btn btn-primary'
- else
  = link_to "New Critique", new_building_bathroom_critique_path(@building,@bathroom,critique), :class => 'btn btn-primary'
%br

= link_to "Go Back", building_path(@building), :class => 'btn'