config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'buildings#index'

  resources :buildings do
    resources :bathrooms do
      resources :critiques
    end
  end

end

app/models/critique.rb
class Critique < ApplicationRecord
  belongs_to :user
  belongs_to :bathroom

  #Simple forms will validate that only integers are accepted
  #We do not need to check for that.

  validates_presence_of :overall_rating, :toilet_rating, :sink_rating,
  :cleanliness_rating, :smell_rating, :privacy_rating
  validates :overall_rating, numericality: {greater_than_or_equal_to: 1, less_than_or_equal_to: 5}
  validates :toilet_rating, numericality: {greater_than_or_equal_to: 1, less_than_or_equal_to: 5}
  validates :sink_rating, numericality: {greater_than_or_equal_to: 1, less_than_or_equal_to: 5}
  validates :cleanliness_rating, numericality: {greater_than_or_equal_to: 1, less_than_or_equal_to: 5}
  validates :smell_rating, numericality: {greater_than_or_equal_to: 1, less_than_or_equal_to: 5}
  validates :privacy_rating, numericality: {greater_than_or_equal_to: 1, less_than_or_equal_to: 5}
  
end

app/controllers/critiques_controller.rb
class CritiquesController < ApplicationController
  before_action :get_building_and_bathroom
  before_action :authenticate_user!

  # Creates a list of all critiques for that bathroom
  def index
    @critiques = @bathroom.critiques
    @current_user_critiques = @critiques.select{ |c| c.user == current_user }
    @other_user_critiques = @critiques.reject{ |c| c.user == current_user }
  end

  # Displays a specific critique.
  # PRE: The critique exists
  # POST: We display info about that critique
  def show
    @critique = @bathroom.critiques.find(params[:id])
  end

  # Redirects to a page for creation of a critique
  # PRE: None
  # POST: None
  def new
    @critique = @bathroom.critiques.new
    @rating_symbols = rating_symbols
  end

  # Creates and stores a new critique in the database
  # PRE: None
  # POST: A new critique is saved in the database
  def create
    @critique = @bathroom.critiques.new(critique_params)
    @critique.user_id = current_user.id
    if @critique.save
      redirect_to(building_bathroom_path(@building,@bathroom))
    else
      render :new
    end
  end

  # Redirects to a page to edit a critique
  # PRE: The critique exists
  # POST: None
  def edit
    @critique = @bathroom.critiques.find(params[:id])
    @rating_symbols = rating_symbols
  end

  # Updates a given critique
  # PRE: The critique exists
  # POST: Changes to the critique are stored in the database
  def update
    @critique = @bathroom.critiques.find(params[:id])
    if @critique.update(critique_params)
      redirect_to(building_bathroom_path(@building,@bathroom))
    else
      render :new
    end
  end

  # Removes a critique
  # PRE: The critique exists
  # POST: The critique is removed from the database
  def destroy
    @critique = @bathroom.critiques.find(params[:id])
    @critique.destroy
    redirect_to(building_bathroom_critiques_path(@building,@bathroom))
  end

  private

  # Specifies the fields that the critique has
  # PRE: None
  # POST: None
  def critique_params
    params.require(:critique).permit(:overall_rating,:toilet_rating,:sink_rating,:cleanliness_rating,:smell_rating,:privacy_rating)
  end

  # Just an array of the ratings as symbols
  def rating_symbols
    [:overall_rating,:toilet_rating,:sink_rating,:cleanliness_rating,:smell_rating,:privacy_rating]
  end

  # Finds the building/bathroom with the specified id
  # PRE: That id is tied to a building/bathroom pair
  # POST: None
  def get_building_and_bathroom
    @building = Building.find(params[:building_id])
    @bathroom = @building.bathrooms.find(params[:bathroom_id])
  end
end

app/views/critiques/edit.html.haml
.container
  %h2 Building: #{@building.name}
  %h3 Bathroom: Floor #{@bathroom.floor} at #{@bathroom.location}

  - if @critique.errors.any?
    %h3
      = pluralize(@critique.errors.count, "error")
      prevented this critique from being modified:
    %ul
      - @critique.errors.full_messages.each do |msg|
        %li= msg
  %br
  = simple_form_for @critique, url: building_bathroom_critique_path(@building,@bathroom) do |f|
    -# Star system based on https://stackoverflow.com/questions/17190111/simple-forms-collection-radio-button-and-custom-label-class
    - @rating_symbols.each do |rating_symbol|
      %h4= rating_symbol.to_s.titleize
      %fieldset
        .star-cb-group
          = f.collection_radio_buttons rating_symbol, [[5], [4], [3], [2], [1]], :first, :last, item_wrapper_tag: false, boolean_style: :inline do |b|
            = b.radio_button + b.label {''}
    %br
    = f.button :submit, :class => 'btn btn-primary'

app/views/critiques/index.html.haml
.container
  %h1 Critiques
  %h3 Building: #{@building.name}
  %h3 Bathroom: Floor #{@bathroom.floor} at #{@bathroom.location}


  %h3 My Critique
  - if @current_user_critiques.empty?
    .panel.panel-warning
      .panel-heading{:style => "text-align:center;"}
        = "Looks like you haven't critiqued this seat!"
        .separator
        = link_to "Create New Critique", new_building_bathroom_critique_path(@building,@bathroom), :class => 'btn btn-primary'
  - else
    %table{:style => "width:100%;", :class => "table table-striped"}
      %thead
        %tr
          %th Overall
          %th Toilet
          %th Sink
          %th Cleanliness
          %th Smell
          %th Privacy
          %th Actions
      %tbody
        - @current_user_critiques.each do |critique|
          %tr
            %td
              = critique.overall_rating
            %td
              = critique.toilet_rating
            %td
              = critique.sink_rating
            %td
              = critique.cleanliness_rating
            %td
              = critique.smell_rating
            %td
              = critique.privacy_rating
            %td
              /= link_to "Show", building_bathroom_critique_path(@building,@bathroom,critique), :class => 'btn'
              = link_to "Edit", edit_building_bathroom_critique_path(@building,@bathroom,critique), :class => 'btn'
              = link_to "Remove", building_bathroom_critique_path(@building,@bathroom,critique), :class => 'btn btn-danger', method: :delete, :data => {confirm: 'Are you sure you want to delete this critique?'}

  .separator

  %h3 Critiques
  - if @other_user_critiques.empty?
    .panel.panel-warning
      .panel-heading{:style => "text-align:center;"}
        = "Looks like no one has critiqued this seat!"
  - else
    %table{:style => "width:100%;", :class => "table table-striped"}
      %thead
        %tr
          %th Overall
          %th Toilet
          %th Sink
          %th Cleanliness
          %th Smell
          %th Privacy
      %tbody
        - @other_user_critiques.each do |critique|
          %tr
            %td
              = critique.overall_rating
            %td
              = critique.toilet_rating
            %td
              = critique.sink_rating
            %td
              = critique.cleanliness_rating
            %td
              = critique.smell_rating
            %td
              = critique.privacy_rating

app/views/critiques/new.html.haml
.container
  %h2 Building: #{@building.name}
  %h3 Bathroom: Floor #{@bathroom.floor} at #{@bathroom.location}

  - if @critique.errors.any?
    %h3
      = pluralize(@critique.errors.count, "error")
      prevented this critique from being added:
    %ul
      - @critique.errors.full_messages.each do |msg|
        %li= msg
  %br
  = simple_form_for @critique, url: building_bathroom_critiques_path(@building,@bathroom) do |f|
    -# Star system based on https://stackoverflow.com/questions/17190111/simple-forms-collection-radio-button-and-custom-label-class
    - @rating_symbols.each do |rating_symbol|
      %h4= rating_symbol.to_s.titleize
      %fieldset
        .star-cb-group
          = f.collection_radio_buttons rating_symbol, [[5], [4], [3], [2], [1]], :first, :last, item_wrapper_tag: false, boolean_style: :inline do |b|
            = b.radio_button + b.label {''}
    %br
    = f.button :submit, :class => 'btn btn-primary'

app/views/critiques/show.html.haml
.container
  %h2 Building: #{@building.name}
  %h3 Bathroom: Floor #{@bathroom.floor} at #{@bathroom.location}

  %table{:style => 'width:100%;'}
    %thead
      %tr
        %th Category
        %th Rating
    %tbody
      %tr
        %td Overall
        %td #{@critique.overall_rating}
      %tr
        %td Toilet
        %td #{@critique.toilet_rating}
      %tr
        %td Sink
        %td #{@critique.sink_rating}
      %tr
        %td Cleanliness
        %td #{@critique.cleanliness_rating}
      %tr
        %td Smell
        %td #{@critique.smell_rating}
      %tr
        %td Privacy
        %td #{@critique.privacy_rating}

  = link_to "Go Back", building_bathroom_critiques_path(@building,@bathroom), :class => 'btn'